sudo: false
language: python
python:
  - 2.7
  - 3.6
  - 3.7

# Install packages
install:
  - pip install numpy
  - python setup.py develop

# Run test
script:
  - python -c "import skfmm, sys; sys.exit(skfmm.test(True))"
